### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by bsudekum** [mlevans/leaflet-hash#1]
Any way we could get more documentation on how this plugin works?

**Comment by mlevans** [comment]
Hi! I'll put up an example soon.

**Comment by bsudekum** [comment]
Awesome, thanks!

**Comment by NelsonMinar** [comment]
What a great little control! Something as simple as this works for me:

```
// Add the leaflet-hash control
var hash = new L.Hash();
hash.init(map);
```

**Comment by glenrobertson** [comment]
+1 the above instruction as well. This control kicks ass btw

**Comment by mlevans** [comment]
Sorry for the delay everyone! I just added a README with some instructions; there's also a live example. You can find everything at http://mlevans.github.com/leaflet-hash/.
