### ISSUE TITLE
I fail to get the Hash to work... in some maps

### ISSUE THREAD

**Issue by Lunkster** [mlevans/leaflet-hash#34]
Hello and I hope you can help me in this probably simple troubles I have. 
I have used the leaflet-hash in a couple of maps and got it to work, i.e. http://meandernatur.se/skyddsvardatrad

When I try to get it to work in another map (AmazonEC2) with identical functionality as the map above except for using geojson instead af ArcMap server-layers, I fail.
http://kajakplatser.se/karta

The code for kajakplatser
http://kajakplatser.se/karta/index.html
http://kajakplatser.se/karta/kajakkarta.js
http://kajakplatser.se/karta/kajakplatser.js

Any ideas?

I have tried different variants of 
        var hash = new L.Hash();
        hash.init(map);
as well as 
.addHash();

Tried to put in on Jsfiddle but probably didnät get all the repositories to work as well as the CORS... http://jsfiddle.net/7mMh7/7/

**Comment by Lunkster** [comment]
Might be related to #13 & #28. But how do I make it ready?

**Comment by mlevans** [comment]
Hi Henrik,

I took a look at this and I think the solution is pretty simple.

You're loading in leaflet-hash before you load mapbox.js. You need to place the code on line 9 in index.html:
 `<script src="./leaflet/assets/map/leaflet-hash.js"></script>` after 
`<script src='//api.tiles.mapbox.com/mapbox.js/v1.5.0/mapbox.js'></script>`.

That works for me. I hope it works for you.

**Comment by Lunkster** [comment]
Ah...  thought it was simple but not that simple :-)
Thanks a lot and keep up the good work.

cheers
Henrik
