### ISSUE TITLE
location.replace(hash) vs location.hash = hash

### ISSUE THREAD

**Issue by VictorVelarde** [mlevans/leaflet-hash#45]
Using `location.hash = hash;` instead of `location.replace(hash);` inside _onMapMove_ allowed me to keep my use case working: a map in a page opened by another page using an anchor. 

I don't know if this breaks anything, but it seems more convenient.

**Comment by AnnieGitUrGun** [comment]
This works for me as well. Thanks @VictorVelarde !

**Comment by VictorVelarde** [comment]
Long time ago... I guess this should be closed
